name: Deploy to Firebase Hosting

# Se ejecuta cuando hay un push en la rama principal
on:
  push:
    branches:
      - main

# Jobs a ejecutar
jobs:
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the code del repositorio
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Configura el entorno de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Actualizado a la versión 18 o superior
      
      # Paso 3: Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Paso 4: Autenticarse con la cuenta de servicio de Firebase
      - name: Authenticate with Firebase using service account
        run: echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > ${HOME}/firebase-key.json

      - name: Set Firebase project
        run: firebase use --add --project ${{ secrets.FIREBASE_PROJECT_ID }}

      # Paso 5: Desplegar en Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}

